platform:ios, "8.0"

target "百思不得姐" do
pod "AFNetworking", "~> 2.5"
pod "SDWebImage"
pod "SVProgressHUD"
pod “MJExtension”
pod “MJRefresh”
pod 'DACircularProgress', '~> 2.3.1'
pod “pop”
pod 'NJKWebViewProgress'
end
